run:
  deadline: 1m
  issues-exit-code: 1
  skip-dirs:
    - testdata$

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
